version: '3.2'
services:
  static_web:
    image: sna-nginx:latest
    build:
      context: ./website
    depends_on:
      - api
    ports:
      - "3000:80"
    volumes:
      - /home/araujo/_development/social-network/website/html:/usr/share/nginx/html
  react_web:
    image: araujo/sna-react:latest
    build:
      context: ./website-react
    depends_on:
      - api
    ports:
      - "3001:3000"
    volumes:
      - /home/araujo/_development/social-network/website-react:/app
      - /app/node_modules
  api:
    image: araujo/sna:latest
    build:
      context: ./api
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "4000:80"
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
