version: '3.2'
services:
  nginx:
    image: sna-nginx
    build:
      context: ./website
    depends_on:
      - api
    ports:
      - "3000:80"
    networks:
      - sna
    volumes:
      - /home/araujo/_development/social-network/website/html:/usr/share/nginx/html
  api:
    image: araujo/sna:latest
    build:
      context: ./api
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "3001:80"
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  sna:
    driver: bridge

volumes:
  website:
  redis_data:
