version: '3.2'
services:
  web:
    image: araujo/sna:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "3000:80"
    volumes:
      - type: bind
        source: ./data
        target: /opt
        volume:
          nocopy: true
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data

volumes:
   data:
   redis_data:
