version: '3.2'
services:
  web:
    image: araujo/sna:3.0
    ports:
      - "3000:80"
    volumes:
      - type: bind
        source: ./data
        target: /opt
        volume:
          nocopy: true

volumes:
   data:
