# Change default server ports
server:
  applicationConnectors:
    - type: http
      port: 3000
  adminConnectors:
    - type: http
      port: 3001

redis:
  host: ${REDIS_HOST:-localhost}

logging:
  level: INFO
  loggers:
    "io.dropwizard": INFO
    "br.com.araujo.socialnetwork":
      level: DEBUG
      additive: true
      appenders:
        - type: file
          currentLogFilename: log/social-network-api.log
          archivedLogFilenamePattern: log/social-network-api-%d.log.gz
          archivedFileCount: 5
  appenders:
    - type: console
