# Change default server ports
server:
  applicationConnectors:
    - type: http
      port: 5000
  adminConnectors:
    - type: http
      port: 5001

redis:
  host: ${REDIS_HOST:-localhost}

consul:
  # Optional properties
  # endpoint for consul (defaults to localhost:8500)
  endpoint: localhost:8500
  # serviceId
  serviceId: social-network-api
  # check interval frequency
  checkInterval: 1 second
  # retry interval frequency
  retryInterval: 5 seconds

logging:
  level: INFO
  loggers:
    "io.dropwizard": INFO
    "br.com.araujo.socialnetwork":
      level: DEBUG
      additive: true
      appenders:
        - type: file
          currentLogFilename: log/social-network-api.log
          archivedLogFilenamePattern: log/social-network-api-%d.log.gz
          archivedFileCount: 5
  appenders:
    - type: console
